[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
game_of_life = "Ge1ccFAwTuKgMY3AYpa9QsU5xCWce9iRiGiSaFa6NL1j"

[programs.localnet]
game_of_life = "2GkfH1VVRkwmqGLiCeWwM31rvRCsJtVkeFJyrzM8cQjB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 10000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
