[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
game_of_life = "2f3VX8BDhBi88secSvgXYnorQcBdyG2ZFwKWcxmMcbAv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 10000000 tests/**/*.ts"


[test]
startup_wait = 5000